version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://user:password@database:5432/symfony_db?serverVersion=15&charset=utf8
    ports:
      - "8000:8000"

  database:
    image: postgres:15
    container_name: symfony_database
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database_data: